//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBInventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_Stock()
        {
            this.Kitchen_Item_Detail = new HashSet<Kitchen_Item_Detail>();
            this.Rooms_Item_Detail = new HashSet<Rooms_Item_Detail>();
        }
    
        public int Item_ID { get; set; }
        public string Item_Name { get; set; }
        public int Item_Quantity { get; set; }
        public Nullable<System.DateTime> Item_Purchased_On { get; set; }
        public Nullable<System.DateTime> Item_Disposed_On { get; set; }
        public string Item_Remarks { get; set; }
        public int Store_ID { get; set; }
    
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitchen_Item_Detail> Kitchen_Item_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rooms_Item_Detail> Rooms_Item_Detail { get; set; }
    }
}
