//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBInventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitchen_Item_Detail
    {
        public int Kitchen_ItemDetail_ID { get; set; }
        public int Kitchen_ID { get; set; }
        public int Kitchen_ItemID { get; set; }
        public int Kitchen_ItemQuantity { get; set; }
        public System.DateTime Kitchen_ItemDate { get; set; }
        public int Kitchen_StoreID { get; set; }
    
        public virtual Item_Stock Item_Stock { get; set; }
        public virtual Kitchen Kitchen { get; set; }
        public virtual Store Store { get; set; }
    }
}
