//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBInventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms_Item_Detail
    {
        public int Rooms_Item_Detail_ID { get; set; }
        public int Room_NumberID { get; set; }
        public int ItemID { get; set; }
        public int ItemQuantity { get; set; }
        public System.DateTime ItemDate { get; set; }
        public int StoreID { get; set; }
    
        public virtual Item_Stock Item_Stock { get; set; }
        public virtual Room_Numbers Room_Numbers { get; set; }
        public virtual Store Store { get; set; }
    }
}
